[package]
name = "rust-db-writer"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]
edition = "2018"

[[bin]]
name = "db-writer"
path = "src/main.rs"

[dependencies]
chrono = "0.4.6"
futures = "0.1.27"
hyper = "0.12.29"
postgres = { version = "0.15.2", features = ["with-chrono"]}
quick-protobuf = "0.6.3"
